### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Synthetize** [Synthetize/password-manager-be#1]
- [x] Add, remove a folder
- [x] Change folder name
- [x] Shoe xisting folders
- [x] Add elements to a folder
- [x] Remove element from a folder
- [x] User vault data encryption
- [x] JWT Refresh token
- [x] Elements name must be unique
- [x] Change user details
- [x] Input sanification
- [x] file reorganizazition
- [x] remove existing refresh token
- [x] remove body from vault delete api
